spring:
  application:
    name: flyingsocks-management
  datasource:
    url: jdbc:mysql://localhost:3306/flyingsocks?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc123lzf
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 600

logging:
  config: classpath:log4j2-dev.xml